# sys.path hack
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from common.osu import OSU_VER_LAZER, OSU_VER_MAX, OSU_VER_MIN, OSU_VER_STR_PREFIX, T_MINUTE, EHideFirst, OsuTimingPoint, almost_bigger, almost_equals, ceil_if_almost_int, f32, get_diffrank_by_name, get_idx_tm_at, get_red_tm_at, get_tm_at, osu_ver_supported
from common.tja import get_course_by_number
from common.utils import print_with_pended

from bisect import bisect_left, bisect_right
from copy import copy
from dataclasses import dataclass
from functools import reduce
import itertools
import sys
import argparse
import codecs
from fractions import Fraction
import os
import math
import traceback
from typing import IO, Callable, Dict, List, Optional, Sequence, Tuple, Union

WATER_MARK = "//Auto generated by osu2tja"

# osu game mode consts
GAMEMODE_STD = 0
GAMEMODE_TAIKO = 1
GAMEMODE_CATCH = 2
GAMEMODE_MANIA = 3

GAMEMODE_TO_STR = {
    GAMEMODE_STD: "osu!std",
    GAMEMODE_TAIKO: "osu!taiko",
    GAMEMODE_CATCH: "osu!catch",
    GAMEMODE_MANIA: "osu!mania",
}

# osu timing effects consts
OSU_TMFX_GGT = 1 << 0
OSU_TMFX_HIDEFIRST = 1 << 3

# osu note type consts
OSU_NOTE_CIRCLE = 1 << 0
OSU_NOTE_SLIDER = 1 << 1
OSU_NOTE_NC = 1 << 2
OSU_NOTE_SPINNER = 1 << 3
OSU_NOTE_HOLD = 1 << 7

# osu hitsound consts
HITSND_NORMAL = 1 << 0
HITSND_WHISTLE = 1 << 1
HITSND_FINISH = 1 << 2
HITSND_CLAP = 1 << 3

# osu event type consts
OSU_EVENT_BG = '0'
OSU_EVENT_VIDEO = 'Video'
OSU_EVENT_BREAK = 'Break'

INT_TO_OSU_EVENT = {
    0: OSU_EVENT_BG,
    1: OSU_EVENT_VIDEO,
    2: OSU_EVENT_BREAK,
}

# tja onp consts
ONP_NONE = '0'
ONP_DON = '1'
ONP_KATSU = '2'
ONP_DON_DAI = '3'
ONP_KATSU_DAI = '4'
ONP_RENDA = '5'
ONP_RENDA_DAI = '6'
ONP_BALLOON = '7'
ONP_END = '8'
ONP_IMO = '9'
ONP_KADON = 'G'

# tja command formatter
FMT_SCROLLCHANGE = lambda x: f'#SCROLL {repr(x)}'
FMT_BPMCHANGE = lambda x: f'#BPMCHANGE {repr(x)}'
FMT_GOGOSTART = lambda: '#GOGOSTART'
FMT_GOGOEND = lambda: '#GOGOEND'
FMT_MEASURECHANGE = lambda x, y: f'#MEASURE {repr(x)}/{repr(y)}'
FMT_BARLINEOFF = lambda: '#BARLINEOFF'
FMT_BARLINEON = lambda: '#BARLINEON'
FMT_DELAY = lambda x: f'#DELAY {repr(x)}'

# ----------------------
# utilities
# ----------------------


def make_cmd(cmd: Union[Callable, "TjaTimedCmd"], *args):
    if isinstance(cmd, TjaTimedCmd):
        cmd, args = cmd.formatter, cmd.args
    return cmd(*args)


def gcd_of_list(l):
    return reduce(math.gcd, l)

# convert time for print


def format_time(t):
    return t//T_MINUTE*100000+t % T_MINUTE


# ----------------------
# parse single line
# ----------------------


def get_section_name(str):
    if str is None:
        return ""
    if str.startswith('[') and str.endswith(']'):
        return str[1:-1]
    return ""


def get_var(str: str) -> Tuple[str, str]:
    if str is None:
        return "", ""
    var_name, _, var_value = str.partition(':')
    return var_name.strip(), var_value.strip()

@dataclass
class OsuEvent:
    event_type: str
    start_time: float
    filename: str = ""
    x_offset: float = 0
    y_offset: float = 0
    end_time: float = 0

def get_event(line: str) -> Optional[OsuEvent]:
    if line is None or line.lstrip().startswith('//'):
        return None

    params = line.split(',', 2)
    if len(params) < 3:
        return None

    event_type, start_time, params = params
    if event_type.isdigit():
        event_type = INT_TO_OSU_EVENT.get(int(event_type), event_type)

    res = OsuEvent(
        event_type = event_type,
        start_time = float(start_time),
    )
    if event_type in {OSU_EVENT_BG, OSU_EVENT_VIDEO}:
        filename, _, params = params.partition(',')
        x_offset, _, params = params.partition(',') # optional
        y_offset, _, params = params.partition(',') # optional
        if filename.startswith('"') and filename.endswith('"'):
            filename = filename[1:-1]
        res.filename = filename
        res.x_offset = float(x_offset or 0)
        res.y_offset = float(y_offset or 0)
    elif event_type == OSU_EVENT_BREAK:
        end_time = float(params.partition(',')[0])
        res.end_time = end_time

    return res


BEAT_RES_MS = 2

def get_beat_res(mspb: float) -> int:
    beat_res = 192 // 4 # start with 1/192nd
    # scale beat_res by power of 2 so that t_unit <= MS_BEAT_RES
    t_unit = mspb / beat_res
    log = int(math.floor(math.log2(t_unit / BEAT_RES_MS)))
    if log > 0:
        beat_res = beat_res << log
    return beat_res

def get_t_unit(tm: OsuTimingPoint) -> float:
    return tm.mspb / tm.beat_res

def get_dt_unit_cnt(t_unit: float, offset0: Union[float, int], offset1: Union[float, int]) -> int:
    delta = (offset1 - offset0) / t_unit
    return int(round(delta))

def get_timing_point(str, prev_timing_point: Optional[OsuTimingPoint] = None) -> Optional[OsuTimingPoint]:
    if str is None:
        return None

    # in case new items are added to osu format
    ps = str.split(',')
    if len(ps) < 2:
        return None

    offset, rawbpmv = ps[:2]
    beats = ps[2] if len(ps) > 2 else '4'
    sevol = ps[5] if len(ps) > 5 else '100'
    uninherited = int(ps[6]) if len(ps) > 6 else float(rawbpmv) > 0
    effects = int(ps[7] if len(ps) > 7 else '0')

    # fill a timing point dict
    ret = OsuTimingPoint(
        offset = float(offset),  # time
        offset_raw = float(offset),
        sevol = float(sevol),
        ggt = ((effects & OSU_TMFX_GGT) != 0),
    )
    if uninherited: # BPM change
        ret.mspb = abs(float(rawbpmv))
        ret.bpm = 60 * 1000.0 / ret.mspb
        ret.beats = abs(int(beats)) # measure change
        ret.beat_res = get_beat_res(ret.mspb)
        ret.scroll = math.copysign(1.0, float(rawbpmv))
        ret.hidefirst = EHideFirst.TO_UNHIDE if (effects & OSU_TMFX_HIDEFIRST) else EHideFirst.SHOWN
        ret.redtm = ret
    else: # SCROLL speed change
        assert prev_timing_point is not None
        merge_with_prev = (
            prev_timing_point.offset_raw == ret.offset_raw
            and prev_timing_point.is_redline()
            and prev_timing_point.ggt == ret.ggt)
        if merge_with_prev:
            ret = prev_timing_point
        else:
            ret.mspb = prev_timing_point.mspb
            ret.bpm = prev_timing_point.bpm
            ret.beat_res = prev_timing_point.beat_res
            ret.beats = prev_timing_point.beats # ignored for inherited timing points
            ret.hidefirst = prev_timing_point.hidefirst # ignored? (use redtm.hidefirst instead)
            ret.redtm = prev_timing_point.redtm
            ret.offset = get_real_offset(ret.offset, raw=True)
        assert ret.redtm is not None
        ret.scroll = -math.copysign(100.0, ret.redtm.scroll) / float(rawbpmv)
        if merge_with_prev:
            if round(ret.offset_raw) in inspect_ms:
                print_with_pended(f"// [INSPECT_MS {ret.offset_raw}] merged timing point {ret}", file=sys.stderr)
            return None # merge uninherited (red) + inherited (green) timing points

    if round(ret.offset_raw) in inspect_ms:
        print_with_pended(f"// [INSPECT_MS {ret.offset_raw}] new timing point {ret}", file=sys.stderr)
    return ret

chart_resources: Dict[str, str] # {'filename': 'type', ...}

timingpoints: List[OsuTimingPoint]
commands_within: List["TjaTimedCmd"]
lasting_note: Optional["TjaTimedNote"]

def init_globals() -> None:
    global timingpoints, balloons, slider_multiplier, slider_tick_rate, overall_difficulty, column_count, gamemode_idx, osu_format_ver, lasting_note
    # global variables
    timingpoints = []
    balloons = []
    slider_multiplier = 1.40
    slider_tick_rate = 4
    overall_difficulty = 5
    column_count = 1
    gamemode_idx = GAMEMODE_STD
    osu_format_ver = 0

    global commands_within, tja_time
    commands_within = []
    tja_time = 0
    lasting_note = None

    global chart_resources
    chart_resources = {}

def init_debug_globals() -> None:
    global show_head_info, output_trace_info, inspect_ms, combo_cnt
    # debug args
    show_head_info = False
    output_trace_info = False
    inspect_ms = {}
    combo_cnt = 0

init_debug_globals()

# get quantized offset by the nearest base timing point
# step 1: find the base timing point around base offset b at or before t
# step 2: calculate the quantized unit count from t to the base timing point
# step 3: get quantized offset from quantized unit count and bpm
# step 4: find the nearest any-color timing points, past point p and future point f
# step 5: adjust quantized offset so that it is at or after point p and before point f


def get_real_offset(dirty_offset: Union[int, float], base_offset: Optional[float] = None, raw: bool = False) -> float:
    if base_offset is None:
        base_offset = dirty_offset
    tm = get_red_tm_at(timingpoints, base_offset, raw)
    t_unit = get_t_unit(tm)
    t_unit_cnt = get_dt_unit_cnt(t_unit, tm.offset, dirty_offset)
    aligned_offset = tm.offset + t_unit_cnt * t_unit

    ret = aligned_offset
    if raw:
        idx_tm_p = get_idx_tm_at(timingpoints, dirty_offset, raw)
        tm_p_offset = timingpoints[idx_tm_p].offset
        if ret < tm_p_offset:
            ret = tm_p_offset
        if round(dirty_offset) in inspect_ms:
            print_with_pended(f"// [INSPECT_MS {dirty_offset}] get_real_offset left-clamp: {dirty_offset - tm_p_offset} from past: {timingpoints[idx_tm_p]}", file=sys.stderr)
        if idx_tm_p + 1 < len(timingpoints):
            tm_f_offset = timingpoints[idx_tm_p + 1].offset
            if ret >= tm_f_offset:
                ret = max(tm_p_offset, tm_f_offset - 1)
            if round(dirty_offset) in inspect_ms:
                print_with_pended(f"// [INSPECT_MS {dirty_offset}] get_real_offset right-clamp: {tm_f_offset - dirty_offset} to future: {timingpoints[idx_tm_p + 1]}", file=sys.stderr)
            if tm_f_offset <= tm_p_offset:
                print_with_pended(f"// Warning: time {aligned_offset} is between timing points at {tm_p_offset} and {tm_f_offset}, with identical offset", file=sys.stderr)

    if round(dirty_offset) in inspect_ms:
        print_with_pended(f"// [INSPECT_MS {dirty_offset}] get_real_offset -> {tm.offset} + {t_unit_cnt} * {t_unit} = {aligned_offset} -> {ret}", file=sys.stderr)
    return ret


def get_slider_sound(str):
    ps = str.split(',')
    reverse_cnt = int(ps[6])
    if len(ps) > 8:
        return [int(x) for x in ps[8].split('|')]
    else:
        return [int(ps[4])] * (reverse_cnt + 1)


def get_hitnote_type(sound: int, column: int):
    is_dai = bool(sound & HITSND_FINISH)
    if column_count <= 1: # Purely keysounded
        is_katsu = bool(sound & (HITSND_CLAP | HITSND_WHISTLE))
    else: # Donkey Konga (KD) / Taiko (KDDK) layout
        n_cols_ka_l = int(math.ceil(column_count / 4))
        n_cols_ka_r = int(column_count / 4)
        is_katsu = (column < n_cols_ka_l or column_count - 1 - column < n_cols_ka_r)
    return ((ONP_KATSU_DAI if is_katsu else ONP_DON_DAI) if is_dai
        else ONP_KATSU if is_katsu else ONP_DON)


# https://github.com/ppy/osu/blob/master/osu.Game.Rulesets.Taiko/Beatmaps/TaikoBeatmapConverter.cs

VELOCITY_MULTIPLIER = 1.4
"""
<summary>
A speed multiplier applied globally to osu!taiko.
</summary>
<remarks>
osu! is generally slower than taiko, so a factor was historically added to increase speed for converts.
This must be used everywhere slider length or beat length is used in taiko.

Of note, this has never been exposed to the end user, and is considered a hidden internal multiplier.
</remarks>
"""

swell_hit_multiplier = 1.65
"""
<summary>
Because swells are easier in taiko than spinners are in osu!,
legacy taiko multiplies a factor when converting the number of required hits.
</summary>
"""

osu_base_scoring_distance: float = 100
"""<summary>
Base osu! slider scoring distance.
</summary>
"""


def get_precision_adjusted_beat_length(sliderVelocity: float, timingControlPoint: OsuTimingPoint) -> float:
    """
    <summary>
    Introduces floating-point errors to post-multiplied beat length for legacy rulesets that depend on it.
    You should definitely not use this unless you know exactly what you're doing.
    </summary>
    """
    sliderVelocityAsBeatLength: float = -100 / sliderVelocity

    # Note: In stable, the division occurs on floats, but with compiler optimisations turned on actually seems to occur on doubles via some .NET black magic (possibly inlining?).
    bpmMultiplier: float = (
        min(max(f32(-sliderVelocityAsBeatLength), 10), 10000) / 100.0
        if sliderVelocityAsBeatLength < 0
        else 1)

    return timingControlPoint.mspb * bpmMultiplier


def should_convert_slider_to_hits(tm: OsuTimingPoint, curve_len: float, reverse_cnt: int) -> Tuple[bool, int, float]:
    isForCurrentRuleset = (gamemode_idx == GAMEMODE_TAIKO)

    # DO NOT CHANGE OR REFACTOR ANYTHING IN HERE WITHOUT TESTING AGAINST _ALL_ BEATMAPS.
    # Some of these calculations look redundant, but they are not - extremely small floating point errors are introduced to maintain 1:1 compatibility with stable.
    # Rounding cannot be used as an alternative since the error deltas have been observed to be between 1e-2 and 1e-6.

    # The true distance, accounting for any repeats. This ends up being the drum roll distance later
    spans: int = reverse_cnt or 1
    distance: float = curve_len

    # Do not combine the following two lines!
    distance *= VELOCITY_MULTIPLIER
    distance *= spans

    timingPoint = tm

    beatLength: float

    if abs(timingPoint.scroll) != 1.0: # modified behavior to support negative scroll
        beatLength = get_precision_adjusted_beat_length(abs(timingPoint.scroll), timingPoint)
    else:
        beatLength = timingPoint.mspb

    sliderScoringPointDistance: float = osu_base_scoring_distance * (slider_multiplier * VELOCITY_MULTIPLIER) / slider_tick_rate

    # The velocity and duration of the taiko hit object - calculated as the velocity of a drum roll.
    taikoVelocity: float = sliderScoringPointDistance * slider_tick_rate
    taikoDuration = int(distance / taikoVelocity * beatLength)

    if isForCurrentRuleset:
        tickSpacing = 0
        return (False, taikoDuration, tickSpacing)

    osuVelocity: float = taikoVelocity * (1000.0 / beatLength)

    # osu-stable always uses the speed-adjusted beatlength to determine the osu! velocity, but only uses it for conversion if beatmap version < 8
    if osu_format_ver >= 8:
        beatLength = timingPoint.mspb

    # If the drum roll is to be split into hit circles, assume the ticks are 1/8 spaced within the duration of one beat
    tickSpacing = min(beatLength / slider_tick_rate, float(taikoDuration) / spans)

    return (tickSpacing > 0
            and distance / osuVelocity * 1000 < 2 * beatLength,
            taikoDuration, tickSpacing)

@dataclass
class TjaTimedNote:
    type: str
    offset: float
    offset_end: float
    column: int
    offset_raw: float
    offset_end_raw: float

def get_note(str_: str, od: float) -> List[TjaTimedNote]:
    global timing_point
    global gamemode_idx
    ret: List[TjaTimedNote] = []

    if str_ is None:
        return ret
    ps = str_.split(',')
    if len(ps) < 5:
        return ret

    column = (min(max(math.floor(float(ps[0]) * column_count / 512), 0), column_count - 1)
        if gamemode_idx == GAMEMODE_MANIA
        else 0)
    type = int(ps[3])
    sound = int(ps[4])
    offset_raw = float(ps[2])
    offset = get_real_offset(offset_raw, raw=True)

    if type & OSU_NOTE_CIRCLE:  # circle
        ret.append(TjaTimedNote(get_hitnote_type(sound, column), offset, offset, column, offset_raw, offset_raw))
        if round(offset_raw) in inspect_ms:
            print_with_pended(f"// [INSPECT_MS {offset_raw}] circle: {ret[-1]}", file=sys.stderr)
    elif type & OSU_NOTE_SLIDER:  # slider, reverse??
        tm = get_tm_at(timingpoints, offset_raw, raw=True)
        curve_len = float(ps[7])
        reverse_cnt = int(ps[6])
        (should_convert, taiko_duration, tick_spacing) = should_convert_slider_to_hits(tm, curve_len, reverse_cnt)

        assert reverse_cnt + 1 == len(get_slider_sound(str_))
        if should_convert:
            slider_sounds = get_slider_sound(str_)
            idx_head = len(ret)
            i = 0
            j = offset_raw
            while j <= offset_raw + taiko_duration + tick_spacing / 8:
                point_offset = get_real_offset(j, raw=True)
                ret.append(TjaTimedNote(get_hitnote_type(slider_sounds[i], column), point_offset, point_offset, column, offset_raw=j, offset_end_raw=j))
                if round(offset_raw) in inspect_ms:
                    print_with_pended(f"// [INSPECT_MS {offset_raw}] slider start {ret[idx_head]}, tick: {ret[-1]}, tm: {tm}", file=sys.stderr)

                j += tick_spacing
                i = (i + 1) % len(slider_sounds)

                if almost_equals(tick_spacing, 0):
                    break
        else:
            offset_end_raw = offset_raw + taiko_duration
            offset_end = get_real_offset(offset_end_raw, raw=True)
            if sound & HITSND_FINISH:
                ret.append(TjaTimedNote(ONP_RENDA_DAI, offset, offset_end, column, offset_raw, offset_end_raw))
            else:
                ret.append(TjaTimedNote(ONP_RENDA, offset, offset_end, column, offset_raw, offset_end_raw))
            ret.append(TjaTimedNote(ONP_END, offset_end, offset_end, column, offset_end_raw, offset_end_raw))

        if round(offset_raw) in inspect_ms:
            print_with_pended(f"// [INSPECT_MS {offset_raw}] slider start: {ret[-2]}, end: {ret[-1]}, tm: {tm}", file=sys.stderr)

    elif type & OSU_NOTE_HOLD:  # hold, converted to circle because overlapping notes are not supported
        tmr = get_red_tm_at(timingpoints, offset_raw, raw=True)
        offset_end = get_real_offset(float(ps[5].split(':', 1)[0]), raw=True)
        taiko_duration = offset_end - offset
        tick_spacing = min(tmr.mspb / slider_tick_rate, float(taiko_duration))
        idx_head = len(ret)
        j = offset_raw
        while j <= offset_raw + taiko_duration + tick_spacing / 8:
            point_offset = get_real_offset(j, raw=True)
            ret.append(TjaTimedNote(get_hitnote_type(sound, column), point_offset, point_offset, column, offset_raw=j, offset_end_raw=j))
            if round(offset_raw) in inspect_ms:
                print_with_pended(f"// [INSPECT_MS {offset_raw}] hold start {ret[idx_head]}, tick: {ret[-1]}, tmr: {tmr}", file=sys.stderr)

            j += tick_spacing

            if almost_equals(tick_spacing, 0):
                break

    elif type & OSU_NOTE_SPINNER:  # spinner
        offset_end_raw = float(ps[5])
        offset_end = get_real_offset(offset_end_raw, raw=True)
        if sound & HITSND_FINISH:
            ret.append(TjaTimedNote(ONP_IMO, offset, offset_end, column, offset_raw, offset_end_raw))
        else:
            ret.append(TjaTimedNote(ONP_BALLOON, offset, offset_end, column, offset_raw, offset_end_raw))
        ret.append(TjaTimedNote(ONP_END, offset_end, offset_end, column, offset_end_raw, offset_end_raw))
        # how many hit will break a ballon
        global balloons
        hit_multiplier = (5 - 2 * (5 - od) / 5 if od < 5
            else 5 + 2.5 * (od - 5) / 5 if od > 5
            else 5) * swell_hit_multiplier
        hits = int(max(1, (offset_end - offset) / 1000 * hit_multiplier))
        balloons.append(hits)

        if round(offset_raw) in inspect_ms:
            print_with_pended(f"// [INSPECT_MS {offset_raw}] spinner start {ret[-2]}, end: {ret[-1]}, hits: {hits}", file=sys.stderr)

    return ret


def get_tsign(tsign_raw: Fraction) -> Tuple[int, int]:
    denominator = tsign_raw.denominator
    numerator = tsign_raw.numerator

    if denominator in (1, 2):
        fix_mul = 4 // denominator
        denominator *= fix_mul
        numerator *= fix_mul

    return (numerator, denominator)


# handle an incomplete bar
# use #MEASURE to write the quantized and unquantized parts as 2 bars
# the remaining time error will be fixed later by aligning tja precision time to osu precision time


def write_incomplete_bar(tm: OsuTimingPoint, bar_data: List[TjaTimedNote], begin, end, tja_contents) -> Tuple[Optional[int], Optional[Tuple[float, float]]]:
    (up_now, low_now) = get_tsign(Fraction(int(tm.beats), 4))
    my_beat_cnt = (end - begin) / tm.mspb

    # this is accurate
    time_bar_data_last = bar_data[-1].offset if len(bar_data) > 0 else begin
    min_beat_cnt = (time_bar_data_last - begin) / tm.mspb

    # calculate #MEASURE for quantized part
    (up_q, low_q) = get_tsign(Fraction(int(round(tm.beat_res * my_beat_cnt)), 4 * tm.beat_res))
    beat_cnt_q = 4 * up_q / low_q
    end_q = get_real_offset(begin + beat_cnt_q * tm.mspb, base_offset=begin)

    if output_trace_info:
        tja_contents.append(f"// [incomplete quantized] {begin}ms + {beat_cnt_q}beats ({up_q}/{low_q}) * {tm.mspb}ms = {begin + beat_cnt_q * tm.mspb}ms -> end_q {end_q}ms")

    # write quantized part
    objs_written_q = None
    if up_q > 0:
        objs_written_q = write_bar_data(tm, bar_data, begin, end_q, tja_contents, time_sig=(up_q, low_q), time_sig_orig=(up_now, low_now), limit=end)
        if objs_written_q is not None:
            (up_now, low_now) = (up_q, low_q)

    # data for unquantized part
    if objs_written_q is not None:
        bar_data = bar_data[objs_written_q:]
    my_beat_cnt_unq = my_beat_cnt - beat_cnt_q
    min_beat_cnt_unq = min_beat_cnt - beat_cnt_q

    # calculate #MEASURE for unquantized part
    (up_unq, low_unq) = get_tsign(Fraction(my_beat_cnt_unq / 4).limit_denominator(48 * 48))

    # avoid the last note to be divided into the next bar
    if len(bar_data) > 0 and min_beat_cnt_unq > 0 and up_unq <= min_beat_cnt_unq / 4 * low_unq:
        up_unq = int(min_beat_cnt_unq / 4 * low_unq) + 1
        # re-simplify the fraction
        (up_unq, low_unq) = get_tsign(Fraction(up_unq, low_unq))
    beat_cnt_unq = 4 * up_unq / low_unq
    end_unq = end_q + beat_cnt_unq * tm.mspb

    if output_trace_info:
        tja_contents.append(f"// [incomplete unquantized] {end_q}ms + {beat_cnt_unq}beats ({up_unq}/{low_unq}) * {tm.mspb}ms = {end_q + beat_cnt_unq * tm.mspb}ms -> end_unq = {end_unq}ms")

    # write unquantized part
    objs_written_unq = None
    if not (up_unq <= 0 and len(bar_data) == 0 and (len(commands_within) == 0 or commands_within[0].offset >= end)):
        # TaikoJiro does not support 0/x measures. Use a <= 1ms measure instead.
        # Note: numerator and denominator can both have decimal places
        if up_unq <= 0:
            (up_unq, low_unq) = (1, 4 * max(1, tm.mspb))
            beat_cnt_unq = 4 * up_unq / low_unq
            end_unq = end_q + beat_cnt_unq * tm.mspb
        assert tm.redtm is not None
        if not tm.redtm.hidefirst.is_hidden():
            tja_contents.append(make_cmd(FMT_BARLINEOFF))
        objs_written_unq = write_bar_data(tm, bar_data, end_q, end_unq, tja_contents, time_sig=(up_unq, low_unq), time_sig_orig=(up_now, low_now), limit=end)
        if objs_written_unq is not None:
            (up_now, low_now) = (up_unq, low_unq)
        if not tm.redtm.hidefirst.is_hidden():
            tja_contents.append(make_cmd(FMT_BARLINEON))

    if objs_written_q is None and objs_written_unq is None:
        return None, None
    return (objs_written_q or 0) + (objs_written_unq or 0), (up_now, low_now)


def write_bar_data(tm: OsuTimingPoint, bar_data: List[TjaTimedNote], begin, end, tja_contents,
    time_sig: Optional[Tuple[float, float]] = None, time_sig_orig: Optional[Tuple[float, float]] = None, limit=None
    ) -> Optional[int]:
    global show_head_info
    global combo_cnt
    global commands_within, tja_time, lasting_note

    if time_sig is None:
        time_sig = (tm.beats, 4)
    if time_sig_orig is None:
        time_sig_orig = time_sig
    if limit is None:
        limit = end

    # ms per quantizing unit
    # ensure correct detection of past-end notes
    has_subdivs = True
    t_unit = get_t_unit(tm)
    if t_unit > end - begin:
        has_subdivs = False
        t_unit = end - begin

    # ignore past-limit notes
    for idx_note_limit in range(len(bar_data), 0, -1):
        last = bar_data[idx_note_limit - 1]
        if (last.offset < limit
            and (not has_subdivs or get_dt_unit_cnt(t_unit, last.offset, end) > 0)
            and get_tm_at(timingpoints, last.offset_raw, raw=True).redtm == tm.redtm
            ):
            break
    else:
        idx_note_limit = 0

    # ignore past-limit commands
    idx_cmd_limit = bisect_left(commands_within, limit, key=lambda cmd: cmd.offset)

    if begin == end and idx_note_limit == 0 and idx_cmd_limit == 0:
        return None

    # build offset data
    offset_list = sorted(set(itertools.chain(
        [begin],
        (max(begin, cmd.offset) for _, cmd in zip(range(idx_cmd_limit), commands_within)
            if cmd.formatter in {FMT_GOGOSTART, FMT_GOGOEND}), # in-range command-time commands
        (max(begin, datum.offset) for _, datum in zip(range(idx_note_limit), bar_data)),
        (max(begin, datum.offset_end) for _, datum in zip(range(idx_note_limit), bar_data)), # consider end offset for overlapping handling
        [max(begin, lasting_note.offset_end)] if lasting_note is not None else [],
        [end],
    )))

    # calculate beat division (no known efficient general solution exists (integer factor problem); do heuristics here)
    time_units = [(offset_list[i], get_dt_unit_cnt(t_unit, begin, offset_list[i])) # force aligned to begin
        for i in range(len(offset_list))]
    time_unit_deltas = [(time_units[i][0], time_units[i][1], time_units[i + 1][1] - time_units[i][1])
        for i in range(len(time_units) - 1)]
    delta_nonzero = [d for t, u, d in time_unit_deltas if d != 0] # ignore sub-quantization intervals
    units_per_div = gcd_of_list(delta_nonzero) if len(delta_nonzero) != 0 else 1

    time_to_div = {t: u // units_per_div for t, u in time_units}
    time_ddivs = [(t, d // units_per_div) for t, u, d in time_unit_deltas if u < units_per_div * time_to_div[end]]

    t_div = units_per_div * t_unit
    divs_target = time_to_div[end]

    # simulate TJAP3 rounding error
    t_div_tja = 4 * T_MINUTE / 16 / tm.bpm * (time_sig[0] / time_sig[1]) * (16 / max(1, divs_target))

    # build notechart definition bar string
    bar_strs: List[str] = []
    idx_cmd = 0
    idx_bar_data = 0
    divs = 0
    begin_of_line = True

    def ensure_begin_of_line():
        nonlocal begin_of_line
        if not begin_of_line:
            bar_strs.append("\n")
        begin_of_line = True

    def goto_offset(offset_curr, offset_target):
        global tja_time
        nonlocal divs, begin_of_line
        if offset_curr == offset_target:
            return offset_target

        if offset_curr not in time_to_div:
            time_to_div[offset_curr] = get_dt_unit_cnt(t_div, begin, offset_curr)
        ddivs = time_to_div[offset_target] - time_to_div[offset_curr]
        delta_ms = ddivs * t_div
        if output_trace_info:
            ensure_begin_of_line()
            bar_strs.append(f"// goto_offset: {offset_curr} -> {offset_target}: {ddivs} divs ({delta_ms})")
            bar_strs.append("\n")
        if ddivs > 0:
            bar_strs.append("0" * ddivs)
            begin_of_line = False
            divs += ddivs
            for _ in range(ddivs):
                tja_time += t_div_tja
        elif ddivs < 0:
            ensure_begin_of_line()
            bar_strs.append(make_cmd(FMT_DELAY, delta_ms / 1000.0))
            bar_strs.append("\n")
            tja_time += delta_ms
        offset = offset_curr + delta_ms
        # extra fix if offset_curr and offset_target have different t_unit
        if ((not has_subdivs or get_tm_at(timingpoints, offset_curr) != tm or get_tm_at(timingpoints, offset_target) != tm)
            and offset != offset_target
            ):
            fix_ms = offset_target - offset
            ensure_begin_of_line()
            bar_strs.append(make_cmd(FMT_DELAY, fix_ms / 1000.0))
            bar_strs.append("\n")
            tja_time += fix_ms
            if output_trace_info:
                ensure_begin_of_line()
                bar_strs.append(f"// goto_fix {fix_ms}")
                bar_strs.append("\n")
        return offset_target

    # floating number offset should match exactly here since they are in the list as-is
    # use <= in case bad things happen
    for offset, delta_divs in time_ddivs:
        # Insert commands
        while idx_cmd < idx_cmd_limit and commands_within[idx_cmd].offset <= offset:
            ensure_begin_of_line()
            bar_strs.append(make_cmd(commands_within[idx_cmd]))
            bar_strs.append("\n")
            idx_cmd += 1

        if delta_divs > 0:
            # Insert a note
            note_type = ONP_NONE
            offset_curr = offset
            while idx_bar_data < idx_note_limit and bar_data[idx_bar_data].offset <= offset:
                note = bar_data[idx_bar_data]
                idx_bar_data += 1

                # combine notes from different columns
                columns = {note.column}
                while idx_bar_data < idx_note_limit and bar_data[idx_bar_data].offset <= offset:
                    note_i = bar_data[idx_bar_data]
                    if note_i.column in columns:
                        break
                    columns.add(note_i.column)
                    notes = {note.type, note_i.type}
                    if notes.issubset({ONP_DON, ONP_DON_DAI}):
                        note.type = ONP_DON_DAI
                    elif notes.issubset({ONP_KATSU, ONP_KATSU_DAI}):
                        note.type = ONP_KATSU_DAI
                    elif notes.issubset({ONP_DON, ONP_DON_DAI, ONP_KATSU, ONP_KATSU_DAI, ONP_KADON}):
                        note.type = ONP_KADON
                    elif notes.issubset({ONP_RENDA, ONP_RENDA_DAI}):
                        note.type = ONP_RENDA_DAI
                    elif notes.issubset({ONP_BALLOON, ONP_IMO}):
                        note.type = ONP_IMO
                    else:
                        break
                    idx_bar_data += 1
                    continue

                # ignore straying roll ends
                if lasting_note is None and note.type == ONP_END:
                    continue

                # complete overlapped roll
                if lasting_note is not None and offset <= lasting_note.offset_end:
                    note_type = ONP_END
                    offset_curr = goto_offset(offset_curr, lasting_note.offset_end)
                    bar_strs.append(ONP_END)
                    begin_of_line = False
                    lasting_note = None
                    divs += 1
                    tja_time += t_div_tja
                    offset_curr += t_div
                    if note.type == ONP_END: # the end is for the overlapped roll
                        continue

                # place the current start
                note_type = note.type
                offset_curr = goto_offset(offset_curr, offset)
                bar_strs.append(note_type)
                begin_of_line = False
                divs += 1
                tja_time += t_div_tja
                offset_curr += t_div

                if note_type in (ONP_DON, ONP_KATSU, ONP_DON_DAI, ONP_KATSU_DAI):
                    combo_cnt += 1
                elif note_type in (ONP_RENDA, ONP_RENDA_DAI, ONP_BALLOON, ONP_IMO):
                    lasting_note = note
                elif note_type == ONP_END:
                    lasting_note = None

            # Insert blanks (if needed)
            if note_type == ONP_NONE and (divs_target > 1 or divs > 1):
                bar_strs.append(note_type)
                divs += 1
                tja_time += t_div_tja
            bar_strs.append("0" * int(delta_divs - 1))
            begin_of_line = False
            divs += int(delta_divs - 1)
            for _ in range(int(delta_divs - 1)):
                tja_time += t_div_tja

    if divs == 0:
        tja_time += t_div_tja

    # remove processed notechart objects
    commands_within = commands_within[idx_cmd:]

    # bar-terminating symbol (1-symbol beat length if comes solely, otherwise zero length)
    bar_strs.append(',')
    begin_of_line = False

    # adjust time signature so that time per div is the same
    time_sig_scaled = time_sig
    if divs > 0 and divs != max(1, divs_target):
        # u/d * 1/divs_target = u'/d' * 1/divs => u'/d' = u/d * divs/divs_target
        try:
            time_sig_scaled = get_tsign(Fraction(time_sig[0] * divs, time_sig[1] * max(1, divs_target))) # type: ignore
        except TypeError:
            time_sig_scaled = (time_sig[0] * divs, time_sig[1] * max(1, divs_target)) # no simplification
    
    if time_sig_scaled != time_sig_orig:
        tja_contents.append(make_cmd(FMT_MEASURECHANGE, time_sig_scaled[0], time_sig_scaled[1]))
        if time_sig_scaled != time_sig:
            # restore after end
            bar_strs.append("\n")
            bar_strs.append(make_cmd(FMT_MEASURECHANGE, time_sig[0], time_sig[1]))
            bar_strs.append("\n")

    bar_str = ''.join(bar_strs)

    if show_head_info:  # show debug info?
        head = "%4d %6.f %s %2d/%2d " % (
            combo_cnt, format_time(begin), repr(units_per_div/tm.beat_res), tm.beat_res, len(bar_str))
        print_with_pended(f"// {head + bar_str}", file=sys.stderr)

    tja_contents.append(bar_str)
    return idx_bar_data


def osu2tja_level(star_osu: float) -> float:
    # 0 to 13 distribution, only a preliminary approximant
    # osu! 0 -> Taiko 1 (OpenTaiko 0)
    # osu! 6 -> Taiko 10 (OpenTaiko 10+)
    # osu! 10 -> OpenTaiko 12+
    min_ = 0.5
    range_ = 12.9374
    exp_base_ = 9.21907
    offset_ = 1.08941
    power_ = 0.514826
    factor_ = range_ / (math.pi / 2)
    return min_ + factor_ * math.atan(math.pow(exp_base_, math.pow(star_osu, power_) - offset_) / factor_)

MS_OSU_MUSIC_OFFSET = 15
"""Ranked osu! beatmaps have late music / early chart sync. osu!'s new audio engine applies a global 15ms chart delay.
<https://github.com/ppy/osu/issues/24625>
"""

MS_OSU_PRE_V5_MUSIC_OFFSET = -24
"""Ranked osu! beatmaps before format v5 had additional early music / late chart sync.
<https://github.com/ppy/osu/discussions/26133>
"""

@dataclass
class TjaTimedCmd:
    offset: float
    formatter: Callable
    args: Sequence

    def __init__(self, offset: float, formatter: Callable, *args):
        self.offset = offset
        self.formatter = formatter
        self.args = args


def osu2tja(fp: IO[str], course: Optional[Union[str, int]] = None, level: Optional[Union[int, float]] = None, audio_name: Optional[str] = None) -> Tuple[
        List[str], List[str], List[str], List[str], Dict[str, str]
    ]:
    init_globals()
    global slider_multiplier, slider_tick_rate, overall_difficulty, column_count, timingpoints
    global balloons
    global osu_format_ver
    global commands_within, tja_time
    global gamemode_idx

    tja_heads_meta: List[str] = []
    tja_heads_sync: List[str] = []
    tja_heads_diff: List[str] = []
    tja_contents: List[str] = []

    # data structures to hold information
    audio = ""
    title = ""
    subtitle = ""
    creator = ""
    artist = ""
    artist_roman = ""
    version = ""
    preview = 0
    hitobjects: List[TjaTimedNote] = []

    preimage = None
    bgmovie = None
    videostart = 0.0

    # state vars
    osu_ver_str = ""
    curr_sec = ""
    # read data
    lines = fp.readlines()
    for lineno, line in enumerate(lines):
        try:
            line = line.strip()
            if line == "":
                continue

            # check osu file format version
            if osu_ver_str == "":
                osu_ver_str = line
                osu_format_ver = int(line.partition(OSU_VER_STR_PREFIX)[2])
                if not osu_ver_supported(osu_format_ver):
                    print_with_pended(f"// Warning: found osu file format v{osu_format_ver}, but only v{OSU_VER_MIN} to v{OSU_VER_MAX} and v{OSU_VER_LAZER} are supported at this moment. The conversion will be performed but might fail.",
                          file=sys.stderr)

            # new section? Update section name.
            new_sec = get_section_name(line)
            if new_sec:
                curr_sec = new_sec
                continue

            # varible? Parse variable
            vname, vval = get_var(line)

            # read in useful infomation in following sections
            if curr_sec == "General":
                if vname == "AudioFilename":
                    root, ext = os.path.splitext(vval)
                    if ext.lower() not in [".ogg", ".mp3"]:
                        vval = root+".ogg"
                    audio = vval
                elif vname == "PreviewTime":
                    preview = int(vval)
                elif vname == "Mode":
                    gamemode_idx = int(vval)

            elif curr_sec == "Metadata":
                if vname in ("Title", "TitleUnicode"):
                    title = vval or title
                elif vname == "Creator":
                    creator = vval
                elif vname == "Version":
                    version = vval
                elif vname == "Source":
                    subtitle = vval
                elif vname == "Artist":
                    artist_roman = artist = vval or artist
                elif vname == "ArtistUnicode":
                    artist = vval or artist
            elif curr_sec == "Difficulty":
                if vname == "CircleSize":
                    if gamemode_idx == GAMEMODE_MANIA:
                        column_count = int(vval)
                elif vname == "SliderMultiplier":
                    slider_multiplier = float(vval)
                elif vname == "SliderTickRate":
                    slider_tick_rate = float(vval)
                elif vname == "OverallDifficulty":
                    overall_difficulty = math.floor(float(vval)) # accuracy, not the actual star rating
            elif curr_sec == "Events":
                data = get_event(line)
                if data:
                    if data.event_type == OSU_EVENT_BG:
                        if preimage is None and data.x_offset == 0:
                            preimage = data.filename
                    elif data.event_type == OSU_EVENT_VIDEO:
                        if bgmovie is None and data.x_offset == 0:
                            bgmovie = data.filename
                            videostart = data.start_time
            elif curr_sec == "TimingPoints":
                prev_timing_point = timingpoints[-1] if len(timingpoints) else None
                data = get_timing_point(line, prev_timing_point)
                if data:
                    timingpoints.append(data)
            elif curr_sec == "HitObjects":
                data = get_note(line, overall_difficulty)
                idx_last = 0
                for obj in data:
                    # fix out-of-order objects for converted osu!mania holds
                    idx_last = bisect_right(hitobjects, obj.offset_raw, lo=idx_last, key=lambda x: x.offset_raw)
                    hitobjects.insert(idx_last, obj)
        except Exception:
            for line in traceback.format_exc().splitlines():
                print_with_pended(f"// {line}", file=sys.stderr)
            print_with_pended(f"// Error parsing `{fp.name}` at line {lineno} in section [{curr_sec}]: `{line}`. Continued.", file=sys.stderr)

    assert len(hitobjects) > 0

    # The music starts at 0ms and (in osu!(stable)) the bar line starts too.
    # add an initial timing point at whole beats non-after the music
    if timingpoints[0].offset > 0:
        tm_first = timingpoints[0]
        init_beats = int(math.ceil(tm_first.offset / tm_first.mspb))
        (init_whole_bars, init_frac_bar_beats) = divmod(init_beats, tm_first.beats)
        new_tms = []

        # timing point for the first beat, if not a whole bar
        if init_frac_bar_beats != 0:
            new_tm_first_frac = copy(tm_first)
            new_tm_first_frac.offset = get_real_offset(
                tm_first.offset - init_beats * tm_first.mspb)
            new_tm_first_frac.beats = init_frac_bar_beats
            new_tm_first_frac.hidefirst = EHideFirst.HIDDEN
            new_tms.append(new_tm_first_frac)

        # timing point for the first whole bar, if any
        if init_whole_bars != 0:
            new_tm_first_whole = copy(tm_first)
            new_tm_first_whole.offset = get_real_offset(
                tm_first.offset - init_whole_bars * tm_first.beats * tm_first.mspb)
            new_tm_first_whole.beats = tm_first.beats
            # hide if the first timing point has hidefirst
            # otherwise follow osu!(stable) and show
            new_tm_first_whole.hidefirst = EHideFirst.HIDDEN if tm_first.hidefirst else EHideFirst.SHOWN
            new_tms.append(new_tm_first_whole)

        if len(new_tms) != 0:
            timingpoints = new_tms + timingpoints

    # collect all non-timing commands
    # these commands will not be broken by #BPMCHANGE or #MEASURE
    assert slider_multiplier is not None
    sv_err_max = 0.00025
    # Ranked osu!taiko beatmaps uses SV 1.40. IID's tja2osu once used SV 1.44 and earlier 1.47.
    base_scroll = (1.0 if 1.40 - sv_err_max <= slider_multiplier <= 1.47 + sv_err_max
        else slider_multiplier / 1.40)
    cur_scroll = 1.0
    cur_ggt = False
    sevol_max = 0
    for tm in timingpoints:
        scroll = tm.scroll * base_scroll
        if scroll != cur_scroll:
            commands_within.append(
                TjaTimedCmd(tm.offset, FMT_SCROLLCHANGE, scroll))
        if tm.ggt != cur_ggt:
            commands_within.append(TjaTimedCmd(tm.offset,
                                    tm.ggt and FMT_GOGOSTART or FMT_GOGOEND))
        if tm.sevol > sevol_max:
            sevol_max = tm.sevol
        cur_scroll = scroll
        cur_ggt = tm.ggt

    BPM = timingpoints[0].bpm
    ms_osu_total_offset = MS_OSU_MUSIC_OFFSET
    if osu_format_ver < 5:
        ms_osu_total_offset += MS_OSU_PRE_V5_MUSIC_OFFSET
    OFFSET = (-timingpoints[0].offset - ms_osu_total_offset) / 1000.0
    DEMOSTART = (preview + ms_osu_total_offset) / 1000.0
    MOVIEOFFSET = (videostart + ms_osu_total_offset) / 1000.0
    SONGVOL = 100 / (sevol_max / 100) if sevol_max > 100 else 100
    SEVOL = sevol_max if sevol_max < 100 else 100

    if gamemode_idx != GAMEMODE_TAIKO:
        str_mode = GAMEMODE_TO_STR.get(gamemode_idx, f"game mode {gamemode_idx}")
        title += f" [{str_mode}]"

    tja_heads_meta.append(WATER_MARK)
    tja_heads_meta.append("TITLE:%s" % (title))
    if subtitle != "":
        subtitle = f'From " {subtitle} "'
        if artist != "":
            subtitle = f"{artist} / {subtitle}"
    tja_heads_meta.append("SUBTITLE:--%s" % (subtitle or artist))
    tja_heads_meta.append("ARTIST:%s" % (artist_roman or artist))
    tja_heads_meta.append("WAVE:%s" % (audio_name or audio))
    tja_heads_meta.append("MAKER:%s" % creator) # for TJAP2fPC-based sims
    tja_heads_meta.append("AUTHOR:%s" % creator) # for Malody

    tja_heads_meta.append("DEMOSTART:%s" % repr(DEMOSTART))

    if preimage:
        tja_heads_meta.append("PREIMAGE:%s" % preimage)
        tja_heads_meta.append("COVER:%s" % preimage) # for Malody
        chart_resources[preimage] = 'preview image'
    if bgmovie:
        tja_heads_meta.append("BGMOVIE:%s" % bgmovie)
        tja_heads_meta.append("MOVIEOFFSET:%s" % repr(MOVIEOFFSET))
        chart_resources[bgmovie] = 'background video'

    tja_heads_sync.append("BPM:%s" % repr(timingpoints[0].bpm))
    tja_heads_sync.append("OFFSET:%s" % repr(OFFSET))

    # not timing syncing, but better to consistent across difficulties
    if SONGVOL != 100:
        tja_heads_sync.append("SONGVOL:%s" % repr(SONGVOL))
    if SEVOL != 100:
        tja_heads_sync.append("SEVOL:%s" % repr(SEVOL))

    str_info_diff_orig = f"// osu! difficulty: {version}"
    tja_heads_diff.append(str_info_diff_orig)
    if course is None:
        course = get_course_by_number(get_diffrank_by_name(version))
    tja_heads_diff.append(f"COURSE:{course}")
    if level is None:
        level = osu2tja_level(overall_difficulty)
    tja_heads_diff.append(f"LEVEL:{level}")  # TODO: GUESS LEVEL

    # don't write score init and score diff
    # taiko jiro will calculate score automatically
    tja_heads_diff.append("BALLOON:%s" % ','.join(map(repr, balloons)))

    tja_contents.append("#START")

    tm_idx = 0  # current timing point index
    obj_idx = 0  # current hit object index
    scroll = timingpoints[0].scroll
    measure = timingpoints[0].beats  # current measure
    curr_bpm = BPM  # current bpm
    curr_barlineon = True

    # current measure states
    obj_idx_begin = 0
    # simulate osu rounding error
    tja_time = bar_offset_end = bar_offset_begin = timingpoints[0].offset
    bar_offset_end += measure * timingpoints[0].mspb

    # ensure correct initial timing
    tja_contents.append(make_cmd(FMT_BPMCHANGE, curr_bpm))
    if measure != 4:
        tja_contents.append(make_cmd(FMT_MEASURECHANGE, measure, 4))

    # check if all notes align ok
    for i, (ho1, ho2) in enumerate(zip(hitobjects[:-1], hitobjects[1:])):
        # allows simultaneous notes
        if ho1.offset > ho2.offset:
            print_with_pended(f"// Warning: Hit object {i}: {ho1} occurs before hit object {i + 1}: {ho2}.", file=sys.stderr)

    # for end of chart
    last_play_event = max(hitobjects[-1].offset if len(hitobjects) > 0 else 0,
        timingpoints[-1].offset if len(timingpoints) > 0 else 0)
    ms_chart_end_padding_max = 1000

    while obj_idx < len(hitobjects) or tm_idx < len(timingpoints) or obj_idx > obj_idx_begin or len(commands_within) > 0:
        # get next object to process
        next_obj = hitobjects[obj_idx] if obj_idx < len(hitobjects) else None

        # get next measure offset to compare
        # skip volumn change and kiai
        while tm_idx < len(timingpoints) and not timingpoints[tm_idx].is_redline():
            tm_idx += 1
        next_redtm = timingpoints[tm_idx] if tm_idx < len(timingpoints) else None

        # check if this object falls into this measure
        end = bar_offset_end
        # bar end aligned to integer or uninherited timing point
        # https://github.com/ppy/osu/issues/28317
        next_redtm_reached = False
        if next_redtm is not None and not almost_bigger(next_redtm.offset, end):
            end = next_redtm.offset
            next_redtm_reached = True
        else:
            end = ceil_if_almost_int(end)

        # collect object
        if next_obj is not None and next_obj.offset < end:
            obj_idx += 1
            continue

        tm = get_tm_at(timingpoints, bar_offset_begin)

        # check end of chart
        t_unit = get_t_unit(tm)
        chart_end = math.inf # unused value
        for padding in [measure * tm.mspb, t_unit * tm.beat_res, ms_chart_end_padding_max]:
            chart_end = get_real_offset(last_play_event + padding, base_offset=bar_offset_begin)
            if chart_end > last_play_event and chart_end <= last_play_event + ms_chart_end_padding_max:
                break
        else:
            chart_end = last_play_event + ms_chart_end_padding_max
        chart_end_reached = False
        if end >= chart_end:
            end = chart_end
            chart_end_reached = True

        # write current measure
        objs_written = None
        measure_changed = False
        assert tm.redtm is not None
        tmr = tm.redtm
        if curr_barlineon != (not tmr.hidefirst.is_hidden()):
            curr_barlineon = not tmr.hidefirst.is_hidden()
            tja_contents.append(make_cmd(FMT_BARLINEON if curr_barlineon else FMT_BARLINEOFF))

        if end == bar_offset_end:
            if output_trace_info:
                tja_contents.append(f"// write_bar_data: {bar_offset_begin}~{end}ms, timing point: {tm}")
            objs_written = write_bar_data(tm, hitobjects[obj_idx_begin:obj_idx], bar_offset_begin, end, tja_contents)
        else:  # collect an incomplete bar?
            if tm_idx > 0: # not the start of the initial bar
                if output_trace_info:
                    tja_contents.append(f"// write_incomplete_bar: {bar_offset_begin}~{end}ms, timing point: {tm}")
                objs_written, measure_written = write_incomplete_bar(tm, hitobjects[obj_idx_begin:obj_idx], bar_offset_begin, end, tja_contents)
                if measure_written is not None and (4 * measure_written[0] / measure_written[1]) != measure:
                    measure_changed = True

        if objs_written is not None:
            obj_idx_begin += objs_written
            # unhide bar line after first measure of hidefirst timing point
            tmr.unhide_first()
        obj_idx = obj_idx_begin

        # go to the next measure
        if chart_end_reached and obj_idx >= len(hitobjects) and len(commands_within) == 0:
            break

        if next_redtm_reached:
            assert next_redtm is not None
            tm = next_redtm
            end = tm.offset

            tm_idx += 1

        if curr_bpm != tm.bpm:
            tja_contents.append(make_cmd(FMT_BPMCHANGE, tm.bpm))
            curr_bpm = tm.bpm
        if measure_changed or measure != tm.beats:
            tja_contents.append(make_cmd(FMT_MEASURECHANGE, tm.beats, 4))
            measure = tm.beats

        # simulate osu rounding error
        bar_offset_end = bar_offset_begin = end
        bar_offset_end += measure * tm.mspb

        if not almost_equals(tja_time, bar_offset_begin, error=1e-3):
            if output_trace_info:
                tja_contents.append(f"// TJA time {tja_time}ms -> osu time {bar_offset_begin}ms")
            # Note: jiro will ignore delays shorter than 0.001s, but tjap3 simulators do not
            # for playing in jiro, use "BPMCHANGEによるズレ調整器" by CurryDry0608hk
            ms_delay = bar_offset_begin - tja_time
            tja_contents.append(make_cmd(FMT_DELAY, ms_delay / 1000))
            tja_time = bar_offset_begin
            # if rewinded, ensure the rewinded part has the correct BPM applied
            if ms_delay < 0:
                tja_contents.append(make_cmd(FMT_BPMCHANGE, tm.bpm))

    tja_contents.append("#END")
    init_debug_globals()
    return tja_heads_meta, tja_heads_sync, tja_heads_diff, tja_contents, chart_resources


def main():
    parser = argparse.ArgumentParser(
        description='Convert an .osu file to .tja format and print the result.',
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("filename", help="source .osu file")
    parser.add_argument("-d", "--debug", action="store_true",
        help="display extra info of converted measures")
    parser.add_argument("-t", "--trace", action="store_true",
        help="log measure conversion info into generated tja")
    parser.add_argument("-i", "--inspect", metavar="ms", type=float, nargs='+', default=[],
        help="display extra info of osu objects placed at specified millisecond offsets")
    parser.add_argument("-g", "--guess-measure", "--guess", action="store_true",
        help="deprecated option intended for forcing skipping predefined integer ratio look-up (now removed) for bar length. Has no effects.")
    args = parser.parse_args()

    global show_head_info, output_trace_info, inspect_ms
    show_head_info = args.debug
    output_trace_info = args.trace
    inspect_ms = set(args.inspect)

    # check filename
    if not args.filename.lower().endswith(".osu"):
        print("// Input file should be Osu file!(*.osu): \n\t[[ %s ]]" % args.filename, file=sys.stderr)
        return

    # try to open file
    try:
        fp = codecs.open(args.filename, "r", "utf8")
        head_meta, head_sync, head_diff, diff_content, recs = osu2tja(fp)
        head_sync_main = head_sync
    except IOError:
        print("// Can't open file `%s`" % args.filename, file=sys.stderr)
        return

    # print results
    print("\n".join(head_meta))
    print("\n".join(head_sync_main))
    print()
    print("\n".join(head_diff))
    print("\n".join(head_sync))
    print("\n")
    print("\n".join(diff_content))


if __name__ == "__main__":
    try:
        main()
    finally:
        input("// Done. Press the Enter key to exit...")
